### ISSUE TITLE
Manager Id is not retained during a creation error

### ISSUE THREAD

**Issue by itsraghz** [raghsonlinedotcom/mini-project-tms#25] opened 2023-01-05 16:54 UTC
https://github.com/raghsonlinedotcom/mini-project-tms/blob/523c2aac70adf79962284acb05daea70428a6c5c/src/main/webapp/create.jsp#L373

Manager Id is not retained during a creation error

**Comment by Arunprasad137** [comment] 2023-01-06 06:27
The Issue Is Fixed Now :)

**Closed as completed by Arunprasad137** 2023-01-06 06:27 UTC
Labels: bug
